# Generated by Django 4.1.3 on 2023-01-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_discription', models.CharField(max_length=100)),
                ('product_number', models.BigIntegerField()),
                ('product_catogari', models.CharField(default='', max_length=20)),
                ('product_stock', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
        ),
    ]
