# Generated by Django 4.1.3 on 2023-01-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discription',
            field=models.CharField(default='', max_length=800),
        ),
    ]
