# Generated by Django 4.1.3 on 2023-02-03 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('sellerpage', '0002_alter_product_product_discription'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('seller_id', models.CharField(max_length=40)),
                ('payment_id', models.CharField(max_length=35)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('payment_id', models.CharField(max_length=35)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerpage.product')),
            ],
        ),
    ]
