# Generated by Django 4.1.3 on 2023-02-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerpage', '0002_alter_product_product_discription'),
        ('customer', '0002_order_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellerpage.product'),
        ),
    ]
